language: csharp
solution: OpenTween.sln

sudo: false

cache:
  directories:
    - ./packages/

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - nuget restore -PackagesDirectory packages
  - msbuild /p:Configuration=Debug /verbosity:quiet
  - mono ./packages/xunit.runner.console/2.3.1/tools/net452/xunit.console.exe ./OpenTween.Tests/bin/Debug/net472/OpenTween.Tests.dll -noappdomain -parallel none
